version: "3.7"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    container_name: kibana
    links:
      - es01
      - es02
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - esnet
  logstash: 
    image: docker.elastic.co/logstash/logstash:7.3.1
    container_name: logstash
    links:
      - es01
      - es02
      - kibana
    volumes:
      # - "./logstash/pipeline/:/usr/share/logstash/pipeline/"
      - "./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./logstash/filter/wiki-filter.conf:usr/share/logstash/wiki-filter.conf"
    networks:
      - esnet
    # environment:
    #   ELASTICSEARCH_HOSTS: es01:9200
    #   KIBANA_HOST: kibana:5601
  filebeat: 
    image: docker.elastic.co/beats/filebeat:7.3.1
    container_name: filebeat
    links:
      - es01
      - es02
      - kibana
    ports:
      - 5044:5044
    volumes:
      - "./filebeat/wiki.xml:/usr/share/filebeat/data/wiki.xml"
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro" 
    networks:
      - esnet
    environment:
      ELASTICSEARCH_HOSTS: es01:9200
      KIBANA_HOST: kibana:5601
volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
networks:
  esnet: